# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Musy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Musy
  pod 'Alamofire'
  pod 'SwipeableTabBarController'
  pod 'AlamofireImage'
  pod 'AlamofireObjectMapper'
  pod 'ObjectMapper'
  pod 'SwiftyJSON'
  pod 'GoogleSignIn'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'PromiseKit'
  pod 'PullUpController'
  pod 'Toast-Swift', '~> 4.0.0'
  pod 'Gallery'
  pod 'MMPlayerView'
 
end
